---
# Docker ,Docker Image ,Docker Container
- name: Run the equivalent of apt-get update as a separate step
  apt:
    update_cache: yes

- name: Install docker and some dependencies
  apt:
    name: python3-pip, docker.io
    state: present

- name: start docker service
  systemd:
    name: docker
    state: started  

- name: Install docker python module
  pip:
    name: docker

- name: Build an image
  docker_image:
    build:
      pull: no
      path: /vagrant/ansible/docker
    name: webnginx
    tag: v1
    force_source: yes
    source: build
        
- name: Create nginx container
  docker_container:
    name: webnginx
    image: webnginx:v1
    state: started
    recreate: yes
    published_ports:
        - 8080:80
