# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false

  config.vm.define "ansible" do |ansible|
    ansible.vm.box="chono-ubuntu-server-v2"
    ansible.vm.hostname = "avm.dob.exam"
    ansible.vm.network "private_network", ip: "192.168.120.100"
    ansible.vm.synced_folder "files/ansible/", "/vagrant"
    ansible.vm.provision "shell", path: "ansible.sh"
  end
  
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box="chono-ubuntu-server-v2"
    jenkins.vm.hostname = "jvm.dob.exam"
    jenkins.vm.network "private_network", ip: "192.168.120.101"
    jenkins.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
    jenkins.vm.synced_folder "files/jenkins/", "/vagrant"
    jenkins.vm.provision "shell", path: "jenkins.sh"
  end
  
  config.vm.define "nagios" do |nagios|
    nagios.vm.box="chono-ubuntu-server-v2"
    nagios.vm.hostname = "nvm.dob.exam"
    nagios.vm.network "private_network", ip: "192.168.120.102"
    nagios.vm.network "forwarded_port", guest: 80, host: 8001, auto_correct: true
    nagios.vm.synced_folder "files/nagios/", "/vagrant"
  end
  
  config.vm.define "docker" do |docker|
    docker.vm.box="chono-ubuntu-server-v2"
    docker.vm.hostname = "dvm.dob.exam"
    docker.vm.network "private_network", ip: "192.168.120.103"
    docker.vm.network "forwarded_port", guest: 80, host: 8082, auto_correct: true
    docker.vm.synced_folder "files/docker/", "/vagrant"
  end

end
