- name: Run the equivalent of apt-get update as a separate step
  apt:
    update_cache: yes
    

- name: Install Apache HTTP Server on Ubuntu
  apt:
    name: apache2
    state: present
    
- name: Start Apache HTTP Server and Enable it on Ubuntu
  service:
    name: apache2
    state: started
    enabled: true
    
- name: Copy web site files to /var/www/html/
  copy:
   dest: /var/www/html/
   src: web/
