# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  

  config.vm.define "ans" do |ans|
    ans.vm.box="chono-ubuntu-server-v2"
    ans.vm.hostname = "ans.dob.lab"
    ans.vm.network "private_network", ip: "192.168.89.100"
    ans.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
    ans.vm.synced_folder "service/", "/vagrant"
    ans.vm.provision "shell", inline: <<EOS
sudo apt update -y
sudo apt install -y ansible
EOS
  end

  config.vm.define "web" do |web|
    web.vm.box="chono-ubuntu-server-v2"
    web.vm.hostname = "web.dob.lab"
    web.vm.network "private_network", ip: "192.168.89.101"
    web.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
    web.vm.synced_folder "service/", "/vagrant"
  end

   config.vm.define "db" do |db|
    db.vm.box="chono-ubuntu-server-v2"
    db.vm.hostname = "db.dob.lab"
    db.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
    db.vm.network "private_network", ip: "192.168.89.102"
    db.vm.synced_folder "service/", "/vagrant"
  end

end
 
