# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false

  config.vm.define "master" do |master|
    master.vm.box="chono-ubuntu-server-v2"
    master.vm.hostname = "master.dob.lab"
    master.vm.network "private_network", ip: "192.168.99.100"
    master.vm.network "forwarded_port", guest: 80, host: 8000
    master.vm.network "forwarded_port", guest: 8080, host: 8080
    master.vm.provision "shell", path: "master.sh"
  end
  
  config.vm.define "slave" do |slave|
    slave.vm.box = "chono-ubuntu-server-v2"
    slave.vm.hostname = "slave.dob.lab"
    slave.vm.network "private_network", ip: "192.168.99.102"
    slave.vm.network "forwarded_port", guest: 80, host: 8088
    slave.vm.provision "shell", path: "slave.sh"
  end

end
