---
# Apache Ubuntu
- name: Run the equivalent of apt-get update as a separate step
  apt:
    update_cache: yes
    

- name: Install Apache HTTP Server on Ubuntu
  apt:
    name: apache2
    state: present
  
- name: start apache server
  systemd:
    name: apache2
    state: started
    enabled: true

  
- name: Delete content & directory
  file:
    state: absent
    path: /var/www/html/
    
- name: Copy web site files to /var/www/html/
  copy:
   dest: /var/www/html/
   src: web/
